services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: microcrm-back
    ports:
      - "8080:8080"
    volumes:
      - app_logs:/var/log/apps
    networks:
      - default
      - elk
    environment:
      - LOG_PATH=/var/log/apps

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: microcrm-front
    ports:
      - "4200:80"
    depends_on:
      - backend
    volumes:
      - app_logs:/var/log/apps
      - ./front/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
      - elk

volumes:
  app_logs:

networks:
  elk:
    external: true
    name: microcrm-elk