sonar.projectKey=LikeAKiwi-dev_P7-FSJA
sonar.organization=likeakiwi-dev
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main,front/src
sonar.tests=back/src/test
sonar.test.inclusions=front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts