sonar.projectKey=LikeAKiwi-dev_P7-FSJA
sonar.organization=likeakiwi-dev
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main,front/src
sonar.tests=back/src/test,front/src
sonar.test.inclusions=back/src/test/**/*,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts

sonar.java.binaries=back/build/classes/java/main
sonar.javascript.lcov.reportPaths=front/coverage/microcrm/lcov.info
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml