server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/apps/frontend/access.log;
    error_log /var/log/apps/frontend/error.log warn;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
