input {
  file {
    path => "/var/log/apps/backend*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
    type => "backend"
  }

  file {
    path => ["/var/log/apps/frontend-access.log", "/var/log/apps/frontend-error.log"]
    start_position => "beginning"
    sincedb_path => "/dev/null"
    type => "frontend"
  }
}

filter {
  if [type] == "backend" {
    mutate {
      add_field => { "app" => "microcrm-back" }
    }
  }

  if [type] == "frontend" {
    mutate {
      add_field => { "app" => "microcrm-front" }
      add_field => { "message_raw" => "%{message}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}